default: &default
  adapter: postgresql
  encoding: unicode
  host: 0.0.0.0
  username: root
  password: 1234
  pool: 5

development:
  <<: *default
  database: rails_painters_development

test:
  <<: *default
  database: rails_painters_dogs_test

production:
  <<: *default
  database: rails_painters_dogs_production